# Load required packages -------------------------------------------------------  
# Input package names
packages <- c("here",
              "readr",
              "stringr", 
              "clock",
              "dplyr",
              "ggplot2",
              "rmarkdown",
              "knitr", 
              "magrittr",
              "glue",
              "xfun",
              "fs") 

installed_packages <- packages %in% rownames(installed.packages())

# Install new packages
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Load packages individually for detection by renv 
library("here")
library("readr")
library("stringr")
library("clock")
library("dplyr")
library("ggplot2")
library("rmarkdown")
library("knitr")
library("magrittr")
library("glue")
library("xfun")
library("fs")

# Load clean data --------------------------------------------------------------  
labour_force <- read_csv(here("data",
                              "clean_data",
                              "labour_force_clean.csv"))    

# Create for loop to automate report generation --------------------------------
# Create data frame of the dot product of all parameter values 
params_df <- expand.grid(unique(labour_force$sex), unique(labour_force$measure),
                         stringsAsFactors = FALSE)  

# Input template report and parameters list to render Rmd reports 
for (i in 1:nrow(params_df)) {
  # Create temp dir using relative paths generated by xfun::from_root()
  temp_output <- xfun::from_root("code", "output")
  fs::dir_create(temp_output)
  
  # Generate output using relative paths generated by xfun::from_root()
  rmarkdown::render(
    input = xfun::from_root("code", "02_create_report_template.Rmd"),
    output_format = github_document(html_preview = FALSE), 
    params = list(sex = params_df[i, 1],
                  measure = params_df[i, 2]),
    output_file = xfun::from_root(temp_output, glue::glue("{params_df[i, 1]}_{params_df[i, 2]}_report.md"))
  )
  
  # Move output folder from ~/code/output to ~/output
  fs::dir_copy(temp_output, xfun::from_root("output"), overwrite = TRUE)
  fs::dir_delete(temp_output)
}