name: ABS_labour_force_report
on:
  # Workflow scheduled to run at 00:00 UTC on the 1st of every month.
  schedule:
    - cron:  "0 0 1 * *"

  # Workflow can also be run manually from the Actions tab
  workflow_dispatch:

# Constructs a job to load the runner, set up the R environment, run scripts and git commit
jobs:
  run_report:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE so your job can access it
      - uses: actions/checkout@v4
      
      # Sets up pandoc which is required for knitting HTML reports  
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1' 

      # Set up R environment 4.1.2
      - name: Setup R version 4.1.2
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
      
      # Set up R packages cache for workflow reruns and restores cache 
      # automatically using renv::restore()   
      - name: Cache R packages
        uses: r-lib/actions/setup-renv@v2
        with:
          cache: true

      # Install cURL to transfer data to virtual environment
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      
      # Executes R scripts
      - name: Extract data from ABS labour force data API 
        run: Rscript code/01_extract_data.R

      - name: Clean raw labour force data
        run: Rscript code/02_clean_data.R

      - name: Render labour force reports
        run: Rscript code/03_automate_reports.R  
      
      # Commits newly rendered reports into the repository 
      - name: Commit new data and reports
        run: |
          git config --local user.email "erikaduan@github.com"
          git config --local user.name "Erika Duan"
          git commit -am ":package: refresh and produce new report version"
          git push 
